# Generated by Django 4.2.7 on 2025-07-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_checked',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='serverconnection',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serverconnection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='serverconnection',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serverlog',
            name='log_type',
            field=models.CharField(choices=[('connection', 'Connection'), ('command', 'Command'), ('error', 'Error'), ('status', 'Status Change')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='serverlog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serverlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['status', 'created_by'], name='servers_ser_status_eca006_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['group'], name='servers_ser_group_i_f527ab_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['-created_at'], name='servers_ser_created_dad2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['created_by', 'status'], name='servers_ser_created_15dc04_idx'),
        ),
        migrations.AddIndex(
            model_name='serverconnection',
            index=models.Index(fields=['user', 'is_active'], name='servers_ser_user_id_2425b4_idx'),
        ),
        migrations.AddIndex(
            model_name='serverconnection',
            index=models.Index(fields=['server', 'is_active'], name='servers_ser_server__0dc2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='serverconnection',
            index=models.Index(fields=['user', 'server'], name='servers_ser_user_id_027b52_idx'),
        ),
        migrations.AddIndex(
            model_name='servergroup',
            index=models.Index(fields=['created_by'], name='servers_ser_created_42987b_idx'),
        ),
        migrations.AddIndex(
            model_name='servergroup',
            index=models.Index(fields=['created_at'], name='servers_ser_created_b82ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['log_type', '-timestamp'], name='servers_ser_log_typ_302915_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['server', 'log_type', '-timestamp'], name='servers_ser_server__7fa566_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['timestamp'], name='servers_ser_timesta_cde26f_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['server', 'user', '-timestamp'], name='servers_ser_server__7ccf20_idx'),
        ),
    ]
